keys:
  - &admin_tygo age1z7ayn0pwy3y3tayaslxfzd867lwuxmqdd8addvags44x8f7fmq4q4f3ce5
  - &host_aerial age1jwqxgpzcqarcezyrr44jgnluhvja73hzcycpu04jr5cksr2g5veqlvrawl
  - &host_balthasar age1zk526p8zwz9qgfxw8tqz8ekc6zyx54kp7kn53s335mxar3gq65wqe2sxap
creation_rules:
  - path_regex: hosts/aerial/secrets.ya?ml$
    key_groups:
    - age:
      - *host_aerial
      - *admin_tygo
  - path_regex: hosts/balthasar/secrets.ya?ml$
    key_groups:
    - age:
      - *host_balthasar
      - *admin_tygo
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *host_aerial
      - *host_balthasar
      - *admin_tygo