set -euo pipefail

operation="${1:-}"
direction="${2:-}"

case "$operation" in
  focus | move | focus-monitor | move-monitor) ;;
  *)
    echo "Usage: niri-directional {focus|move|focus-monitor|move-monitor} {left|right|up|down}" >&2
    exit 2
    ;;
esac

case "$direction" in
  left | right | up | down) ;;
  *)
    echo "Usage: niri-directional {focus|move|focus-monitor|move-monitor} {left|right|up|down}" >&2
    exit 2
    ;;
esac

# Monitor directions follow the physical output layout, regardless of the
# focused output's window layout axis.
case "$operation" in
  focus-monitor) exec niri msg action "focus-monitor-$direction" ;;
  move-monitor) exec niri msg action "move-column-to-monitor-$direction" ;;
esac

focused_output="$(
  niri msg --json focused-output |
    jq --exit-status --raw-output '.name'
)"

is_vertical=false

# NIRI_VERTICAL_OUTPUTS is a colon-separated list generated by Nix.
IFS=':' read -ra vertical_outputs <<< "${NIRI_VERTICAL_OUTPUTS:-}"

for output in "${vertical_outputs[@]}"; do
  if [[ "$focused_output" == "$output" ]]; then
    is_vertical=true
    break
  fi
done

if [[ "$is_vertical" == true ]]; then
  # On the vertical-layout output, the two layout axes are visually rotated.
  case "$operation:$direction" in
    focus:up)    action="focus-column-left" ;;
    focus:down)  action="focus-column-right" ;;
    focus:left)  action="focus-window-up" ;;
    focus:right) action="focus-window-down" ;;

    move:up)     action="move-column-left" ;;
    move:down)   action="move-column-right" ;;
    move:left)   action="move-window-up" ;;
    move:right)  action="move-window-down" ;;
  esac
else
  # Regular horizontal scrolling layout.
  case "$operation:$direction" in
    focus:left)  action="focus-column-left" ;;
    focus:right) action="focus-column-right" ;;
    focus:up)    action="focus-window-up" ;;
    focus:down)  action="focus-window-down" ;;

    move:left)   action="move-column-left" ;;
    move:right)  action="move-column-right" ;;
    move:up)     action="move-window-up" ;;
    move:down)   action="move-window-down" ;;
  esac
fi

exec niri msg action "$action"
